version: '3.7'

services: 
  db:
    image: mysql/mysql-server:latest
    volumes:
        - ./sql:/docker-entrypoint-initdb.d
        - db_data:/var/lib/mysql
    restart: always
    #ports:
    #    - '3306:3306'
    #networks:
    #    - db
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: meal_project
      MYSQL_ROOT_HOST: '%'
      #MYSQL_USER: wordpress
      #MYSQL_PASSWORD: wordpress

  app:
    build: 
      context: ./app
    volumes: 
      - static_data:/vol/web
    command: gunicorn meal_project.wsgi:application --bind 0.0.0.0:8000
    environment: 
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=meal_project.settings.dev_mysql
      - SECRET_KEY=samplessecretkey123
      - ALLOWED_HOSTS=localhost
    expose:
      - '8000'
    depends_on: 
      - db
    #networks:
    #  - db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - app

volumes: 
  static_data:
  db_data:

#networks:
#  db:
#    driver: bridge
