version: '3.3'

services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    restart: always
    #environment:
    #  MYSQL_ROOT_HOST: '%'
    #  MYSQL_ROOT_PASSWORD: 'test_pass' # TODO: Change this
    #  MYSQL_USER: 'test'
    #  MYSQL_PASS: 'pass'
    ports:
      - '3307:3307'
    expose:
      - '3307'
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume: