# Generated by Django 2.2 on 2019-09-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_meals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['ingredients__aisle']},
        ),
    ]
