# Generated by Django 2.2.10 on 2020-04-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20200412_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='meals',
            field=models.ManyToManyField(blank=True, to='meals.Meal'),
        ),
    ]
