# Generated by Django 2.2.13 on 2020-10-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_cart_yearweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_details',
            name='found',
            field=models.BooleanField(default=False),
        ),
    ]
