# Generated by Django 2.2 on 2019-09-01 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_meal_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal_details',
            options={'ordering': ['ingredient__aisle']},
        ),
    ]
