# Generated by Django 2.2.7 on 2019-11-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_auto_20190902_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='details',
        ),
    ]
