# Generated by Django 2.2.24 on 2022-04-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_auto_20211024_0626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart_details',
            options={},
        ),
    ]
