# Generated by Django 5.2.11 on 2026-03-06 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0014_auto_20230715_1733"),
        ("meals", "0011_alter_meal_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="meals",
        ),
        migrations.CreateModel(
            name="MealSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "slot_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("generic", "Generic"),
                        ],
                        default="dinner",
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=50)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="carts.cart"
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="meals.meal",
                    ),
                ),
            ],
        ),
    ]
