# Generated by Django 4.2.19 on 2025-03-04 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0010_alter_meal_details_id"),
        ("carts", "0014_auto_20230715_1733"),
    ]

    operations = [
        migrations.CreateModel(
            name="Days",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="cart",
            name="meals",
        ),
        migrations.CreateModel(
            name="Meals",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="carts.cart"
                    ),
                ),
                ("days", models.ManyToManyField(to="carts.days")),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="meals.meal"
                    ),
                ),
            ],
        ),
    ]
