# Generated by Django 5.2.12 on 2026-03-07 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0015_remove_cart_meals_mealslot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart_details",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_details",
                to="carts.cart",
            ),
        ),
        migrations.AlterField(
            model_name="mealslot",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_slots",
                to="carts.cart",
            ),
        ),
    ]
