# Generated by Django 4.2.19 on 2025-03-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0015_days_remove_cart_meals_meals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="days",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
