# Generated by Django 2.2.24 on 2021-11-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
