# Generated by Django 5.2.11 on 2026-02-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='walk_mode',
            field=models.CharField(choices=[('standard', 'Standard (1 → N)'), ('reverse', 'Reverse (N → 1)')], default='standard', max_length=10),
        ),
    ]
