# Generated by Django 5.2.11 on 2026-03-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0004_store_walk_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="walk_mode",
            field=models.CharField(
                choices=[
                    ("standard", "Standard (1 → N)"),
                    ("reverse", "Reverse (N → 1)"),
                    ("custom", "Custom Layout"),
                ],
                default="standard",
                max_length=10,
            ),
        ),
    ]
