# Generated by Django 5.2.11 on 2026-03-01 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0005_alter_store_walk_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreAisleOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aisle", models.DecimalField(decimal_places=1, max_digits=4)),
                ("walk_order", models.PositiveIntegerField()),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aisle_orders",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "ordering": ["walk_order"],
                "unique_together": {("store", "aisle")},
            },
        ),
    ]
