# Generated by Django 5.2.11 on 2026-03-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0006_storeaisleorder"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="storeaisleorder",
            index=models.Index(
                fields=["store", "walk_order"], name="stores_stor_store_i_41a62f_idx"
            ),
        ),
    ]
