# Generated by Django 5.2.11 on 2026-03-01 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0007_storeaisleorder_stores_stor_store_i_41a62f_idx"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="storeaisleorder",
            unique_together={("store", "aisle"), ("store", "walk_order")},
        ),
    ]
