# Generated by Django 3.2.18 on 2023-07-15 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_id'),
        ('carts', '0013_auto_20230715_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='yearweek',
            field=models.IntegerField(),
        ),
    ]
