# Generated by Django 2.2.9 on 2020-01-20 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_remove_meal_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['aisle']},
        ),
    ]
