"""
Django settings for a_core project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Project title displayed in the header
PROJECT_TITLE = "Project Title"


# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-rj#-z^kx3j+1ay397otg6j8m_8#v^$^$jys6&41vy^&6le)ezc'
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', "change_me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv(
    "DJANGO_ALLOWED_HOSTS",
    "localhost,127.0.0.1"
).split(",")

ALLOWED_HOSTS = [h for h in ALLOWED_HOSTS if h]

# Application definition

INSTALLED_APPS = [
    "app.carts",
    "app.meals",
    "app.ingredients",
    "app.users",
    "app.stores",
    "app.metrics",
    "crispy_forms",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "app.meal_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "app.meal_project.context_processors.store_renderer",
            ]
        },
    }
]

WSGI_APPLICATION = "app.meal_project.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "appdb_dev"),
        "USER": os.getenv("POSTGRES_USER", "appuser_dev"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "strong_password_here"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": 5432,
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
# Directory where `collectstatic` will gather static files for production.
# It must NOT be the same as any path listed in `STATICFILES_DIRS`.
STATIC_ROOT = str(BASE_DIR / "staticfiles")

# Additional locations the staticfiles app will search (project-level static assets).
# Keep your source static files in `BASE_DIR/static/` and let `collectstatic`
# copy them into `STATIC_ROOT` (staticfiles) for serving in production.
STATICFILES_DIRS = [
    str(BASE_DIR / "static"),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media' 

CRISPY_TEMPLATE_PACK = "bootstrap4"

LOGIN_REDIRECT_URL = "meals-home"
LOGIN_URL = "login"

def parse_trusted_origins(raw_origins, default_scheme="http://"):
    """
    Converts a comma-separated string into a list of origins with schemes.
    Adds default_scheme if missing.
    Filters out empty strings.
    """
    return [
        o if o.startswith(("http://", "https://")) else f"{default_scheme}{o}"
        for o in (origin.strip() for origin in raw_origins.split(","))
        if o
    ]
