name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v4

    - name: QEMU Configuration 
      uses: docker/setup-qemu-action@v3

    - name: "Set up Docker Buildx"
      uses: "docker/setup-buildx-action@v3"

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} 

    - name: "Build and push image tags"
      uses: "docker/build-push-action@v5"
      with:
        context: "."
        file: "./app/Dockerfile"
        platforms: "linux/arm64"
        sbom: true
        push: true
        tags: |
          "sshoemake/meal_project:latest"
          "sshoemake/meal_project:${{ github.ref_name }}"
