name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Action
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build the Docker image
    - run: |
        docker build . --file ./app/Dockerfile --tag ghcr.io/sshoemake/meal_project:latest
        docker push ghcr.io/sshoemake/meal_project:latest        
